

// 13. iconMap.tsx
import {
  Car,
  Utensils,
  Shrub,
  Truck,
  Bike,
  Anchor,
  Plane,
  Tent,
  Tractor,
  Church,
  Milestone,
  Mountain,
  MapPinned,
  Siren,
  Sun,
  Castle,
  Megaphone,
  Ambulance,
  TrafficCone,
  CarFront,
  TowerControl,
  CloudRain,
  Caravan,
  Cctv,
  Telescope,
  Caravan as Van,
  Check,
  RefreshCcw,
} from "lucide-react";
import { FaHatCowboySide } from "react-icons/fa";
import { TbCamper, TbRollercoaster, TbHelicopter } from "react-icons/tb";
import { IoFastFoodOutline, IoCarSportSharp, IoCloudOutline } from "react-icons/io5";
import { MdLocalGasStation } from "react-icons/md";
import { PiBarnDuotone, PiPoliceCarFill, PiWindmill } from "react-icons/pi";
import { FaBridge, FaCarTunnel, FaFerry, FaMotorcycle, FaMountainCity } from "react-icons/fa6";

export const iconMap = {
  car: <Car />,
  utensils: <Utensils />,
  cowboy: <FaHatCowboySide />,
  coffee: <MdLocalGasStation />,
  trafficCone: <TrafficCone />,
  trainTrack: <Milestone />,
  windmill: <PiWindmill />,
  waves: <Anchor />,
  tent: <Tent />,
  mountain: <Mountain />,
  milestone: <Milestone />,
  shrub: <Shrub />,
  bridge: <FaBridge />,
  truck: <Truck />,
  megaphone: <Megaphone />,
  motorcycle: <FaMotorcycle />,
  policeCar: <PiPoliceCarFill />,
  siren: <Siren />,
  carFront: <CarFront />,
  camper: <TbCamper />,
  fastFood: <IoFastFoodOutline />,
  telescope: <Telescope />,
  rollercoaster: <TbRollercoaster />,
  tractor: <Tractor />,
  towerControl: <TowerControl />,
  carTunnel: <FaCarTunnel />,
  gasStation: <MdLocalGasStation />,
  ferry: <FaFerry />,
  sun: <Sun />,
  boombox: <Megaphone />,
  sportCar: <IoCarSportSharp />,
  bike: <Bike />,
  barn: <PiBarnDuotone />,
  castle: <Castle />,
  rain: <CloudRain />,
  cloud: <IoCloudOutline />,
  caravan: <Van />,
  mountainCity: <FaMountainCity />,
  plane: <Plane />,
  helicopter: <TbHelicopter />,
  ambulance: <Ambulance />,
  mapPinned: <MapPinned />,
  church: <Church />,
  windTurbine: <PiWindmill />,
  cctv: <Cctv />,
  anchor: <Anchor />,
};
