// 13. iconMap.tsx
import {
  Car,
  Utensils,
  Shrub,
  Truck,
  Bike,
  Anchor,
  Plane,
  Tent,
  Tractor,
  Church,
  Milestone,
  Mountain,
  MapPinned,
  Siren,
  Sun,
  Castle,
  Megaphone,
  Ambulance,
  TrafficCone,
  CarFront,
  TowerControl,
  CloudRain,
  Caravan,
  Cctv,
  Telescope,
  Caravan as Van,
  Check,
  RefreshCcw,
  Wind,
  Ship,
} from "lucide-react";
import { FaHatCowboySide, FaHelicopter } from "react-icons/fa";
import { TbCamper, TbRollercoaster, TbHelicopter } from "react-icons/tb";
import {
  IoFastFoodOutline,
  IoCarSportSharp,
  IoCloudOutline,
} from "react-icons/io5";
import { MdLocalGasStation } from "react-icons/md";
import { PiBarnDuotone, PiPoliceCarFill, PiWindmill } from "react-icons/pi";
import {
  FaBridge,
  FaCarTunnel,
  FaFerry,
  FaMotorcycle,
  FaMountainCity,
} from "react-icons/fa6";
import { GiTowTruck, GiWindTurbine } from "react-icons/gi";

export const iconMap = {
  car: <Car size={28} />,
  utensils: <Utensils size={28} />,
  cowboy: <FaHatCowboySide size={28} />,
  coffee: <MdLocalGasStation size={28} />,
  trafficCone: <TrafficCone size={28} />,
  trainTrack: <Milestone size={28} />,
  windmill: <PiWindmill size={28} />,
  waves: <Anchor size={28} />,
  tent: <Tent size={28} />,
  mountain: <Mountain size={28} />,
  milestone: <Milestone size={28} />,
  shrub: <Shrub size={28} />,
  bridge: <FaBridge size={28} />,
  truck: <Truck size={28} />,
  megaphone: <Megaphone size={28} />,
  motorcycle: <FaMotorcycle size={28} />,
  policeCar: <PiPoliceCarFill size={28} />,
  siren: <Siren size={28} />,
  carFront: <CarFront size={28} />,
  camper: <TbCamper size={28} />,
  fastFood: <IoFastFoodOutline size={28} />,
  telescope: <Telescope size={28} />,
  rollercoaster: <TbRollercoaster size={28} />,
  tractor: <Tractor size={28} />,
  towerControl: <TowerControl size={28} />,
  carTunnel: <FaCarTunnel size={28} />,
  gasStation: <MdLocalGasStation size={28} />,
  ferry: <Ship size={28} />,
  sun: <Sun size={28} />,
  boombox: <Megaphone size={28} />,
  sportCar: <IoCarSportSharp size={28} />,
  bike: <Bike size={28} />,
  barn: <PiBarnDuotone size={28} />,
  castle: <Castle size={28} />,
  rain: <CloudRain size={28} />,
  cloud: <IoCloudOutline size={28} />,
  caravan: <Van size={28} />,
  mountainCity: <FaMountainCity size={28} />,
  plane: <Plane size={28} />,
  helicopter: <FaHelicopter size={28} />,
  ambulance: <Ambulance size={28} />,
  mapPinned: <MapPinned size={28} />,
  church: <Church size={28} />,
  windTurbine: <GiWindTurbine size={28} />,
  cctv: <Cctv size={28} />,
  anchor: <Anchor size={28} />,
  towtruck: <GiTowTruck size={28} />,
};
